name: Jest Test Reporter
description: Report Jest test statistics to Google Sheets for coding challenges
author: Oluwasetemi Ojo
inputs:
  challenge:
    description: Comma-separated list of challenges or tasks to report on
    required: true
    example: task-1,task-2,task-3
  lang:
    description: Programming language in use (javascript, python, php)
    required: true
    example: javascript
  server:
    description: Base API URL for the reporting service
    required: true
    example: https://api.example.com
  sheetid:
    description: Google Spreadsheet ID for storing results
    required: true
    example: 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms
  token:
    description: Authentication token for API calls
    required: true
    example: ghp_xxxxxxxxxxxxxxxxxxxx
runs:
  using: node22
  main: dist/index.js
branding:
  icon: bar-chart-2
  color: green
