name: Test Results Reporter
description: Report test statistics to Google Sheets for coding challenges
author: Oluwasetemi Ojo
inputs:
  challenge:
    description: Comma-separated list of challenges or tasks to report on
    required: true
    example: task-1,task-2,task-3
  lang:
    description: Programming language in use (javascript, python, php)
    required: true
    example: javascript
  server:
    description: Base API URL for the reporting service(sheetson API base URL)
    required: true
    example: https://api.example.com
  sheetid:
    description: Google Spreadsheet ID for storing results
    required: true
    example: 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms
  token:
    description: Authentication token for API calls
    required: true
    example: xxxxxxxxxxxxxxxxxxxx
  sheet:
    description: Google Spreadsheet name for storing results(ensure the sheet is created in the spreadsheet and contains the column names you are posting to - exactly matching the column names in the spreadsheet)
    required: true
    example: month1
runs:
  using: node20
  main: dist/index.js
branding:
  icon: bar-chart-2
  color: green
